export const OtpTypes = Object.freeze({
    EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
    PASSWORD_RESET: 'PASSWORD_RESET',
    LOGIN: 'LOGIN',
    CHANGE_EMAIL: 'CHANGE_EMAIL',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    SENSITIVE_ACTION: 'SENSITIVE_ACTION',
});
